import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import * as D from './dsp.mjs';
import { renderMusic, varietyCheck, validateSpec, resolveSpec, PRESETS, PROGRESSIONS } from './music.mjs';
import { renderSfx, SFX_TYPES, PACKS } from './sfx.mjs';
import { analyze, silences } from './audio.mjs';
import { ff, probe, toWav48, has, run, die, log, readJson, writeJson, mkdirp, workDir, stateDir, SKILL_DIR, ffmpeg } from './util.mjs';

import {geometry, FORMATS} from '../../assets/template/src/lib/format.mjs';

// ---------------- project
export function cmdNew(a) {
  const dest = path.resolve(a._[0] || 'my-video'); if (fs.existsSync(dest) && fs.readdirSync(dest).length) die(`${dest} is not empty`);
  fs.cpSync(path.join(SKILL_DIR, 'assets', 'template'), dest, { recursive: true });
  const style = a.style || 'pi-v2'; const sp = path.join(SKILL_DIR, 'styles', style, 'tokens.json'); if (!fs.existsSync(sp)) die(`unknown style ${style}`, `choose one of: ${fs.readdirSync(path.join(SKILL_DIR, 'styles')).join(', ')}`);
  fs.copyFileSync(sp, path.join(dest, 'src', 'style.json'));
  const format=a.format || (a.vertical?'9:16':'16:9');const g=geometry(format,a.platform);
  { const j=readJson(path.join(dest,'src','style.json'));j.canvas={...j.canvas,width:g.width,height:g.height};writeJson(path.join(dest,'src','style.json'),j); }
  { const t = readJson(path.join(dest, 'src', 'style.json')); const mod = (n) => n.replace(/[^A-Za-z0-9]/g, ''); // load the style's Google Fonts
    const wts = [...new Set(Object.values(t.font.weights || {}).map(String).concat(['400', '500']))].sort();
    fs.writeFileSync(path.join(dest, 'src', 'lib', 'fonts.ts'), `// Generated by motioncraft new from style.json. To change fonts: import another family from @remotion/google-fonts
// (or use @remotion/fonts with a local file in public/fonts) AND update style.json font.display / font.mono.
import {loadFont as loadDisplay} from '@remotion/google-fonts/${mod(t.font.display)}';
import {loadFont as loadMono} from '@remotion/google-fonts/${mod(t.font.mono)}';
loadDisplay('normal', {weights: ${JSON.stringify(wts)}, subsets: ['latin']});
loadMono('normal', {weights: ['400', '500'], subsets: ['latin']});
`); }
  writeJson(path.join(dest, 'mc.config.json'), { title: a.title || path.basename(dest), style, handle: a.handle || '@yourhandle', format, platform:g.platform, fps: 30 });
  return { created: dest, style, next: [`cd ${dest}`, 'ASK the user, then: npm install', 'npm run studio  (preview)'] };
}

// ---------------- music / sfx / mix
export function cmdMusic(a) {
  const sub = a._[0];
  if (sub === 'presets') return { presets: PRESETS, progressions: Object.fromEntries(Object.entries(PROGRESSIONS).map(([k, v]) => [k, v.mood])) };
  const spec = a.spec ? readJson(path.resolve(a.spec)) : {}; if (a.preset) spec.preset = a.preset;
  for (const k of ['bpm', 'duration', 'drop', 'swing', 'seed']) if (a[k] != null) spec[k] = +a[k];
  for (const k of ['key', 'lead', 'comp', 'drums', 'progression']) if (a[k] != null) spec[k] = a[k];
  const s = resolveSpec(spec); const issues = validateSpec(s); if (issues.length) die('music spec rejected:\n  - ' + issues.join('\n  - '), 'fix the values or pick a preset: node scripts/motioncraft.mjs music presets');
  const hist = path.join(os.homedir(), '.motioncraft', 'music-history.json'); const H = readJson(hist, []);
  const v = varietyCheck(s, H[H.length - 1]); if (!v.ok && !a.force) die(`too similar to the last track (${v.why.join(', ')}). Change at least 2 of key / bpm (>=6) / progression / lead.`, 'or pass --force if the user explicitly wants the same vibe');
  const outDir = path.resolve(a.out || 'audio'); mkdirp(outDir);
  if (sub === 'audition') { // 3 short variations
    const res = []; const keys = ['C', 'D', 'F', 'G', 'A', 'Bb']; const progs = Object.keys(PROGRESSIONS);
    for (let i = 0; i < 3; i++) { const vs = { ...spec, duration: 16, drop: 5, key: keys[(keys.indexOf(s.key) + 1 + i * 2) % keys.length], progression: progs[(progs.indexOf(s.progression) + 1 + i) % progs.length], bpm: s.bpm + [-4, 0, 5][i], chords: undefined, seed: 7 + i };
      const r = renderMusic(vs); const m = D.master(r.mix); const f = path.join(outDir, `audition_${i + 1}.wav`); D.writeWav(f, m.buf, 16, fs); res.push({ file: f, key: r.spec.key, bpm: r.spec.bpm, progression: r.spec.progression }); }
    return { auditions: res, next: 'let the user pick one, then run `music make` with those values' };
  }
  const r = renderMusic(s); const m = D.master(r.mix, a.lufs ? +a.lufs : -14, -1);
  D.writeWav(path.join(outDir, 'music.wav'), m.buf, 24, fs);
  if (a.stems) for (const [k, b] of Object.entries(r.stems)) D.writeWav(path.join(outDir, `stem_${k}.wav`), b, 16, fs);
  const grid = { bpm: r.spec.bpm, beatSeconds: 60 / r.spec.bpm, beats: r.beats, sections: r.markers, duration: r.dur };
  writeJson(path.join(outDir, 'beatgrid.json'), grid);
  mkdirp(path.dirname(hist)); H.push({ key: s.key, bpm: s.bpm, chords: s.chords, lead: s.lead, at: new Date().toISOString() }); writeJson(hist, H.slice(-20));
  return { music: path.join(outDir, 'music.wav'), beatgrid: path.join(outDir, 'beatgrid.json'), lufs: +m.lufs.toFixed(2), truePeak: +m.truePeak.toFixed(2), duration: +r.dur.toFixed(2), sections: r.markers, spec: { preset: s.preset, bpm: s.bpm, key: s.key, progression: s.progression, lead: s.lead } };
}
export function cmdSfx(a) {
  if (a._[0] === 'list') return { types: SFX_TYPES, packs: Object.keys(PACKS) };
  const cuesFile = a.cues || (a.timeline ? null : 'sfx.json'); let cues = [], dur = +a.duration || 0, bpm = a.bpm ? +a.bpm : null;
  if (a.timeline) { const tl = readJson(path.resolve(a.timeline)); cues = tl.sfx || []; dur = dur || tl.duration; bpm = bpm || tl.bpm; }
  else { const j = readJson(path.resolve(cuesFile)); if (!j) die(`cannot read ${cuesFile}`, 'pass --cues file.json ([{type,t}]) or --timeline timeline.json'); cues = Array.isArray(j) ? j : j.cues; dur = dur || j.duration || Math.max(...cues.map((c) => c.t)) + 3; }
  const r = renderSfx(cues, dur, { bpm, pack: a.pack || 'soft-pop', density: a.density ? +a.density : 1 });
  const o = path.resolve(a.out || 'audio/sfx.wav'); mkdirp(path.dirname(o)); D.writeWav(o, r.buf, 24, fs);
  return { sfx: o, cues: cues.length, perMinute: Math.round(cues.length / (dur / 60)), warnings: r.warnings };
}
export function cmdMix(a) {
  const load = (p) => p ? D.readWav(toWav48(path.resolve(p), path.basename(p) + '.wav'), fs).buf : null;
  const vo = load(a.vo), music = load(a.music), sfx = load(a.sfx); if (!vo && !music) die('need at least --vo or --music');
  const n = Math.max(...[vo, music, sfx].filter(Boolean).map((b) => b.L.length)); const mix = D.stereo(n);
  let voP = null; if (vo) { voP = D.compress(D.filt(vo, 'hp', 80), -20, 3, 5, 120); D.mixInto(mix, voP); }
  if (music) { let m = D.gain(D.clone(music), D.db(a.musicDb ? +a.musicDb : -6));
    if (voP) { // duck music under VO + dip 1-4 kHz so words stay clear
      const env = new Float32Array(n); const at = Math.exp(-1 / (0.01 * D.SR)), rt = Math.exp(-1 / (0.35 * D.SR)); let e = 0;
      for (let i = 0; i < n; i++) { const l = i < voP.L.length ? Math.abs(voP.L[i]) + Math.abs(voP.R[i]) : 0; e = l > e ? at * e + (1 - at) * l : rt * e + (1 - rt) * l; env[i] = e; }
      const dip = D.filt(m, 'peak', 2500, 0.8, -3);
      for (let i = 0; i < m.L.length; i++) { const k = Math.min(1, env[i] * 12); const g = 1 - k * (1 - D.db(-7)); m.L[i] = (m.L[i] * (1 - k) + dip.L[i] * k) * g; m.R[i] = (m.R[i] * (1 - k) + dip.R[i] * k) * g; } }
    D.mixInto(mix, m); }
  if (sfx) D.mixInto(mix, sfx, D.db(a.sfxDb ? +a.sfxDb : -4));
  let finalMix=mix;
  if (a.duration != null) { const seconds=Number(a.duration); if(!Number.isFinite(seconds)||seconds<=0)die('--duration needs positive seconds');
    const samples=Math.round(seconds*D.SR);if(mix.L.length<samples)die(`mix sources too short for ${seconds}s (${(mix.L.length/D.SR).toFixed(2)}s); extend music/VO before mixing`);
    finalMix=D.stereo(samples);finalMix.L.set(mix.L.subarray(0,samples));finalMix.R.set(mix.R.subarray(0,samples));
    const fade=Math.min(samples,Math.round(0.35*D.SR));for(let i=0;i<fade;i++){const g=(fade-i-1)/fade;finalMix.L[samples-fade+i]*=g;finalMix.R[samples-fade+i]*=g;}
  }
  const M = D.master(finalMix, a.lufs ? +a.lufs : -14, -1.5); const o = path.resolve(a.out || 'audio/final.wav'); mkdirp(path.dirname(o)); D.writeWav(o, M.buf, 24, fs);
  return { final: o, lufs: +M.lufs.toFixed(2), truePeak: +M.truePeak.toFixed(2), duration: +(finalMix.L.length / D.SR).toFixed(2) };
}

// ---------------- analysis
export function cmdAudio(a) { const f = a._[1] || a._[0]; if (!f) die('usage: audio analyze <file>'); const w = toWav48(path.resolve(f)); const r = analyze(w); if (a.out) writeJson(path.resolve(a.out), r); return a.full ? r : { ...r, beats: `${r.beats.length} beats`, onsets: `${r.onsets.length} onsets`, energyDbPerHalfSecond: undefined, note: 'use --full or --out file.json for all beat/onset times; key is an estimate (see confidence)' }; }
export function cmdBeat(a) {
  const sub = a._[0];
  if (sub === 'grid') { const bpm = +a.bpm, dur = +a.dur, off = +(a.offset || 0), fps = +(a.fps || 30); if (!bpm || !dur) die('usage: beat grid --bpm 93 --dur 52.6 [--offset 0] [--fps 30]'); const beats = []; for (let t = off; t < dur; t += 60 / bpm) beats.push(+t.toFixed(4)); return { bpm, beats, bars: beats.filter((_, i) => i % 4 === 0), frames: beats.map((t) => Math.round(t * fps)) }; }
  if (sub === 'snap') { const cues = readJson(path.resolve(a._[1])); const grid = readJson(path.resolve(a.grid || 'audio/beatgrid.json')); const max = (+a.maxMs || 80) / 1000;
    const snapped = cues.map((c) => { let best = grid.beats[0]; for (const b of grid.beats) if (Math.abs(b - c.t) < Math.abs(best - c.t)) best = b; return Math.abs(best - c.t) <= max ? { ...c, t: best, snapped: true } : c; });
    if (a.out) writeJson(path.resolve(a.out), snapped); return { snapped: snapped.filter((c) => c.snapped).length, total: cues.length, cues: snapped }; }
  die('usage: beat grid|snap');
}
export function cmdVo(a) {
  const sub = a._[0]; const f = path.resolve(a._[1] || 'audio/vo.wav');
  if (sub === 'clean') { const o = path.resolve(a.out || f.replace(/\.\w+$/, '_clean.wav')); ff(['-i', f, '-af', 'highpass=f=80,afftdn=nf=-25,loudnorm=I=-16:TP=-1.5:LRA=7', '-ar', '48000', o]); return { cleaned: o }; }
  if (sub === 'align') { // word timings via Whisper if present, else phrase timings from silences
    const o = path.resolve(a.out || 'audio/words.json'); const py = has('python3') ? 'python3' : has('python') ? 'python' : null;
    if (py && run(py, ['-c', 'import faster_whisper']).status === 0) {
      const r = run(py, [path.join(SKILL_DIR, 'scripts', 'py', 'whisper_words.py'), f, o, a.lang || 'auto', a.model || 'small']); if (r.status !== 0) die('whisper failed: ' + r.stderr.slice(-400));
      const j = readJson(o); return { words: j.words.length, text: j.text, file: o, mode: 'word', check: 'Compare `text` with the script. Names are often misheard; if a segment looks wrong, cut it with ffmpeg and transcribe that piece alone.' };
    }
    const w = D.readWav(toWav48(f), fs); const mono = w.buf.L; const sil = silences(mono, 48000, -40, 0.18); const dur = mono.length / 48000; const phrases = []; let st = 0;
    for (const [s0, s1] of sil) { if (s0 - st > 0.2) phrases.push({ start: +st.toFixed(3), end: +s0.toFixed(3) }); st = s1; } if (dur - st > 0.2) phrases.push({ start: +st.toFixed(3), end: +dur.toFixed(3) });
    const script = a.script ? fs.readFileSync(path.resolve(a.script), 'utf8').split(/(?<=[.!?])\s+|\n+/).map((x) => x.trim()).filter(Boolean) : [];
    writeJson(o, { mode: 'phrase', phrases: phrases.map((p, i) => ({ ...p, text: script[i] || null })), words: [] });
    return { file: o, mode: 'phrase', phrases: phrases.length, scriptSentences: script.length, warning: script.length && script.length !== phrases.length ? 'phrase count differs from script sentences: check the pauses by ear or adjust --script line breaks' : undefined, note: 'Whisper not found: word-level sync unavailable. Words are spread evenly inside each phrase by `timeline build`.' };
  }
  die('usage: vo clean|align <file>');
}
export function cmdTimeline(a) {
  const words = readJson(path.resolve(a.words || 'audio/words.json'), { words: [], phrases: [] }); const grid = readJson(path.resolve(a.grid || 'audio/beatgrid.json'), { beats: [] });
  let W = words.words || [];
  if (!W.length && words.phrases?.length) for (const p of words.phrases) { const ws = (p.text || '').split(/\s+/).filter(Boolean); ws.forEach((w, i) => W.push({ w, start: +(p.start + (p.end - p.start) * i / ws.length).toFixed(3), end: +(p.start + (p.end - p.start) * (i + 1) / ws.length).toFixed(3) })); }
  const dur = +(a.duration || Math.max(grid.duration || 0, W.length ? W[W.length - 1].end + 2.5 : 0));
  const tl = { duration: +dur.toFixed(3), bpm: grid.bpm || null, words: W, beats: grid.beats || [], sections: grid.sections || [], scenes: [], events: [] };
  const o = path.resolve(a.out || 'public/timeline.json'); writeJson(o, tl); return { timeline: o, words: W.length, beats: tl.beats.length, duration: tl.duration };
}

// ---------------- reference breakdown
export function cmdRef(a) {
  const sub = a._[0]; const dir = path.resolve(a.dir || 'ref'); mkdirp(dir); const vid = path.join(dir, 'ref.mp4');
  if (sub === 'get') { const src = a._[1]; if (!src) die('usage: ref get <url|file>');
    if (/^https?:/.test(src)) { if (!has('yt-dlp')) die('yt-dlp not installed', 'ask the user to install it (see doctor) or to download the video and run `ref get <file>`'); const r = run('yt-dlp', ['-f', 'bv*[height<=1080]+ba/b', '--merge-output-format', 'mp4', '-o', vid, src], { stdio: 'inherit' }); if (r.status !== 0) die('download failed'); }
    else ff(['-i', path.resolve(src), '-c:v', 'libx264', '-crf', '18', '-c:a', 'aac', vid]);
    const p = probe(vid); const v = p.streams.find((s) => s.codec_type === 'video'); return { file: vid, duration: +(+p.format.duration).toFixed(2), size: `${v.width}x${v.height}`, fps: v.r_frame_rate }; }
  if (!fs.existsSync(vid)) die(`${vid} not found`, 'run `ref get <url|file>` first');
  if (sub === 'scenes') { const r = ff(['-i', vid, '-vf', `select='gt(scene,${a.threshold || 0.3})',showinfo`, '-f', 'null', '-']); const cuts = [...r.stderr.matchAll(/pts_time:([\d.]+)/g)].map((m) => +(+m[1]).toFixed(2)); writeJson(path.join(dir, 'scenes.json'), cuts); return { cuts, count: cuts.length, file: path.join(dir, 'scenes.json') }; }
  if (sub === 'frames') { const fd = path.join(dir, 'frames'); mkdirp(fd); const every = +(a.every || 0.5); ff(['-i', vid, '-vf', `fps=1/${every},scale=640:-2`, '-q:v', '3', path.join(fd, 'f_%04d.jpg')]); const n = fs.readdirSync(fd).length; return { dir: fd, frames: n, every }; }
  if (sub === 'sheet') { const fd = path.join(dir, 'frames'); if (!fs.existsSync(fd)) die('run `ref frames` first'); const files = fs.readdirSync(fd).filter((f) => f.endsWith('.jpg')).sort(); const every = +(a.every || 0.5); const per = 20; const sheets = [];
    for (let s = 0; s * per < files.length; s++) { const o = path.join(dir, `sheet_${s + 1}.jpg`); ff(['-start_number', String(s * per + 1), '-i', path.join(fd, 'f_%04d.jpg'), '-frames:v', '1', '-vf', `drawtext=text='%{eif\\:(n+${s * per})*${every}\\:d}s':x=8:y=8:fontsize=22:fontcolor=white:box=1:boxcolor=black@0.5,tile=5x4:padding=6:margin=6`, o]); sheets.push(o); }
    return { sheets, note: 'Open each sheet image and describe: layout, type sizes, color, motion between frames, where cuts land.' }; }
  if (sub === 'motion') { const r = ff(['-i', vid, '-vf', 'scale=320:-2,tblend=all_mode=difference,signalstats,metadata=print:key=lavfi.signalstats.YAVG', '-f', 'null', '-']); const v = [...r.stderr.matchAll(/YAVG=([\d.]+)/g)].map((m) => +m[1]); const fps = 30; const perSec = []; for (let i = 0; i < v.length; i += fps) perSec.push(+(v.slice(i, i + fps).reduce((x, y) => x + y, 0) / Math.min(fps, v.length - i)).toFixed(2)); return { motionPerSecond: perSec, note: 'higher = more movement; flat low = holds; spikes = transitions' }; }
  if (sub === 'colors') { const o = path.join(dir, 'palette.png'); ff(['-i', vid, '-vf', 'fps=1,scale=160:-2,palettegen=max_colors=12:stats_mode=full', o]); return { palette: o, note: 'open the image; the swatches are the dominant colors' }; }
  if (sub === 'audio') { const w = toWav48(vid, 'ref.wav'); const r = analyze(w); writeJson(path.join(dir, 'audio.json'), r); return { ...r, beats: `${r.beats.length} beats`, onsets: `${r.onsets.length}`, energyDbPerHalfSecond: undefined, file: path.join(dir, 'audio.json') }; }
  if (sub === 'text') { if (!has('tesseract')) die('tesseract not installed', 'optional: skip OCR, read text from the sheets instead'); const fd = path.join(dir, 'frames'); const res = []; for (const f of fs.readdirSync(fd).filter((x) => x.endsWith('.jpg')).sort().filter((_, i) => i % 2 === 0)) { const r = run('tesseract', [path.join(fd, f), '-', '--psm', '11']); const t = (r.stdout || '').replace(/\s+/g, ' ').trim(); if (t) res.push({ frame: f, text: t }); } writeJson(path.join(dir, 'text.json'), res); return { found: res.length, file: path.join(dir, 'text.json') }; }
  if (sub === 'report') { const out = []; for (const s of ['scenes', 'frames', 'sheet', 'motion', 'colors', 'audio']) { try { out.push([s, cmdRef({ ...a, _: [s] })]); } catch (e) { out.push([s, { error: String(e) }]); } }
    const R = Object.fromEntries(out); const md = [`# Reference report`, '', `Video: ${vid}`, '', `## Cuts (${R.scenes.count})`, R.scenes.cuts.join(', '), '', `## Music`, `BPM ${R.audio.bpm}, key ${R.audio.key} (conf ${R.audio.confidence}), LUFS ${R.audio.lufs}, drop ${JSON.stringify(R.audio.drop)}`, '', `## Motion per second`, R.motion.motionPerSecond.join(' '), '', `## Contact sheets`, ...R.sheet.sheets.map((s) => `- ${s}`), '', `Palette: ${R.colors.palette}`, '', '## TODO for the agent', '- open every sheet and fill: typography (font feel, sizes, weights), layout, color use, motion vocabulary, transitions, how text syncs to VO, how cuts sit on the beat', '- write findings into styles/<new>/style.md and tokens.json (see references/customization.md)'].join('\n');
    fs.writeFileSync(path.join(dir, 'ref_report.md'), md); return { report: path.join(dir, 'ref_report.md') }; }
  die('usage: ref get|scenes|frames|sheet|motion|colors|audio|text|report');
}
